### ISSUE TITLE
Public API: GET v1.2/project/{projectId}/todolist/{todoListId}/item possible bug

### ISSUE THREAD

**Issue by DmitryLapshov** [getroadmap/roadmap#4060]
@RoadmapTeam 
I can see the same todo item with the different requests. But in the first case Resources is Null. In the second case it's an array (not empty). In the first case Attributes = Null. In the second case it's an empty array (Help indicates that it should be Null). I don't know what an expected correct behavior is to validate the responses properly.
```
GETting https://testing.ppmroadmap.com/v1.2/project/93467/todolist/239496/item: 200 OK
[
  {
    "TodoListID": 239496,
    "Completed": false,
    "CompletedDate": null,
    "WorkItemType": "Todo",
    "ID": 1688129,
    "ProjectID": 93467,
    "Name": "To-Do Item 1436963546",
    "StartDate": "2015-07-15T00:00:00",
    "DueDate": "2015-08-14T00:00:00",
    "Resources": null,
    "Attributes": null
  }
]

GETting https://testing.ppmroadmap.com/v1.2/project/93467/todolist/239496/item/1688129: 200 OK
{
  "TodoListID": 239496,
  "Completed": false,
  "CompletedDate": null,
  "WorkItemType": "Todo",
  "ID": 1688129,
  "ProjectID": 93467,
  "Name": "To-Do Item 1436963546",
  "StartDate": "2015-07-15T00:00:00",
  "DueDate": "2015-08-14T00:00:00",
  "Resources": [
    {
      "ID": 823173,
      "Resource": {
        "ID": 104847,
        "CustomCode": "Resource Custom Code 1436963546",
        "ResourceCode": "104847",
        "Name": "Resource 1436963546"
      },
      "Role": {
        "ID": 27790,
        "Name": "Role 1436963546"
      },
      "Estimate": {
        "Time": 100.0,
        "Unit": "Percent"
      }
    }
  ],
  "Attributes": []
}
```

**Comment by AndrewKaplanovsky** [comment]
@DmitryLapshov, That's right. Public API call  
/project/{projectID}/todolist/{listID}/item returns the list of _all_ todo list items. In this case we return only basic information about items, assigned resources and custom attributes are not retrieved. 
/project/{projectID}/todolist/{listID}/item/{itemID} returns the information about a particular todo item, and in this case we retrieve full information about the item, including assigned resources and custom attributes.  

I've updated the API call doc appropriately to reflect this behavior.
