### ISSUE TITLE
"Error 0" using BCX

### ISSUE THREAD

**Issue by bkingbking** [getroadmap/roadmap#4073]
@NPC I was seeing a lot of errors with the extension for a few minutes -- on projects connected with / without Roadmap -- then the errors cleared-up. See below for screenshots.

@hbarrington Any way to see if the errors correspond to any anomalies in New Relic?  Errors occurred approximately 8:30 - 8:40pm EST tonight (July 20).

![extension error](https://cloud.githubusercontent.com/assets/2389362/8790808/222c7718-2f20-11e5-86c7-1659ba3eceff.gif)

![screen shot 2015-07-20 at 8 38 25 pm](https://cloud.githubusercontent.com/assets/2389362/8790813/2c938ff2-2f20-11e5-9499-57425704aa4b.png)

![screen shot 2015-07-20 at 8 39 07 pm](https://cloud.githubusercontent.com/assets/2389362/8790815/2f956a40-2f20-11e5-91a7-2f026129b10c.png)

**Comment by NPC** [comment]
There doesn't seem to be anything related in the server-side API log for today: https://api.ppmroadmap.com/logs/publicAPI/2015-07-20.txt, so this failed before even getting to API processing logic. 

This morning I briefly saw a Redis error on our Staging API. It is a different server, and the time doesn't coincide, but perhaps it is worth checking if Redis or another potential intermediate stage was down at the time on our public API server?

PS So many mappingsext calls in the log! I need to think how to reduce them for the browser extension.

@bkingbking @hbarrington

**Comment by bkingbking** [comment]
Would this error be caused by a bad or dropped wifi connection? There's an outside chance that my wifi connection faded in / out when the errors occurred.

**Comment by NPC** [comment]
Bill, it could be, I receive the same error if I quickly unplug my WiFi while doing a BCX page refresh.

@bkingbking

**Comment by bkingbking** [comment]
I'm going to close this ticket for now. The behavior was very unusual, and with no log reports to validate it, my guess is that it was a wifi issue.
